# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: ericda/sentiment-classifier:latest

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Download training data
          command: |
            mkdir -p data
            cd data
            mv /opt/sentiment-classifier/data/aclImdb_v1.tar.gz .
            mv /opt/sentiment-classifier/data/wiki-news-300d-1M.vec.zip .
            tar -xzf aclImdb_v1.tar.gz
            unzip wiki-news-300d-1M.vec.zip

      - run:
          name: Run unit tests
          command: |
            . venv/bin/activate
            export $(cat .env | xargs)
            # python -m unittest discover -s tests;  # TODO: fix test order
            python -m unittest tests/test_preprocessing.py
            python -m unittest tests/test_reader.py
            python -m unittest tests/test_ml.py
            python -m unittest tests/test_api.py

      - store_artifacts:
          path: test-reports
          destination: test-reports
