# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
            - data

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: download data
          command: |
            mkdir -p data
            cd data
            wget http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz
            tar -xvzf aclImdb_v1.tar.gz
            wget https://dl.fbaipublicfiles.com/fasttext/vectors-english/wiki-news-300d-1M.vec.zip
            tar -xvf wiki-news-300d-1M.vec.zip

      - save_cache:
          paths:
            - ./data/aclImdb
            - ./data/wiki-news-300d-1M.vec
          key: data

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            export $(cat .env | xargs)
            python -m unittest discover -s tests;

      - store_artifacts:
          path: test-reports
          destination: test-reports
